In [2]:
import numpy as np
np.random.seed(42)

In [45]:
a = np.arange(1,13).reshape(2,3,2)
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [46]:
a = a.cumprod(axis=-1)
a

array([[[  1,   2],
        [  3,  12],
        [  5,  30]],

       [[  7,  56],
        [  9,  90],
        [ 11, 132]]])

In [47]:
a[:,:, -1]

array([[  2,  12,  30],
       [ 56,  90, 132]])

In [56]:
# t = 5
# (a>t).argmax(axis=-1)

a = a.reshape((-1,a.shape[2]))
a[np.arange(a.shape[0]),(a>t).argmax(axis=-1)].reshape()

array([ 1, 12, 30,  7,  9, 11])

In [30]:
tmp = (a>t).all(axis=1)

In [34]:
tmp * a[np.arange(a.shape[0]),-1] + (1-tmp) * a[np.arange(a.shape[0]),(a>t).argmax(axis=1)]

array([        12,        150, 9526572000])

In [33]:
(1-tmp) * a[np.arange(a.shape[0]),(a>t).argmax(axis=1)]

array([ 12, 150,   0])

In [35]:
a.ndim

2

In [84]:
gaoling_return = np.array([5,3,3,3,2.5,2,2,2,1.5,0.7]) ### 高瓴股票三年收益乘数的分布估计
gaoling_return = np.array([5.5,3,3,2.5,2.5,2,1.8,1.0,0.7,0.5]) ### 高瓴股票三年收益乘数的分布估计
# gaoling_return = np.array([5,3.5,2.5,2.5,2.5,1.7,1.8,1.5,1,0.7]) ### 高瓴股票三年收益乘数的分布估计
assert gaoling_return.shape == (10,)

In [85]:
## 算术平均数与几何平均数
def f(x):
    cal_mu = np.mean(x)
    geo_mu = np.power(np.prod(x),1.0/x.shape[0])
    print('%.2f, %.2f, %.2f' %(cal_mu, geo_mu, cal_mu-geo_mu)) 
f(gaoling_return)

2.25, 1.82, 0.43


In [83]:
# def f2(x):
#     for i in range(1,20):
#         tmp = np.power(x, 1.0/i)
#         tmp = np.power(np.mean(tmp),i)
#         print('%s:  %.4f' %(str(i).rjust(2,'0'), tmp)) 
# f2(gaoling_return)